### PR TITLE
HUB 943 ruumba

### PR DESCRIPTION
**Pull request by PatKelsh**

### CODE REVIEW

**Comment by jondandois** [comment]
can you add a note to README:Testing about Ruumba?

**Comment by jondandois** [comment]
Getting lots of errors for semicolons in the code, but there are no semicolons in the code where ruumba thinks there are.

**Comment by PatKelsh** [comment]
@jondandois did you run ruumba with the configuration file `ruumba app/ -D -c .ruumba.yml`

**Comment by jondandois** [comment]
@PatKelsh yes, i ran at just as you said: 
```
Inspecting 58 files
.C.....................CC.CCC.....C...C...C...............

Offenses:

/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:14:71: C: Rails/Date: Do not use Date.today without zone. Use Time.zone.today instead.
    date_status = until_date && Date.parse(body['until_date']) < Date.today ? "expired" : "until"
                                                                      ^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:21:80: C: Rails/Date: Do not use Date.today without zone. Use Time.zone.today instead.
    elsif body['until_date'].present? && Date.parse(body['until_date']) < Date.today
                                                                               ^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:63:65: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                            hubzone_status_style ;      visibility     
                                                                ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:63:66: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                            hubzone_status_style ;      visibility     
                                                                 ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:63:67: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                            hubzone_status_style ;      visibility     
                                                                  ^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:70:83: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                               aria_hubzone_status ;       hubzone_status         
                                                                                  ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:70:84: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                               aria_hubzone_status ;       hubzone_status         
                                                                                   ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:70:85: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                               aria_hubzone_status ;       hubzone_status         
                                                                                    ^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:73:54: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
              t('sidebar.date_status.' + date_status) ;     until_date   
                                                     ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:73:55: C: Style/Semicolon: Do not use semicolons to terminate expressions.
              t('sidebar.date_status.' + date_status) ;     until_date   
                                                      ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:73:56: C: Layout/ExtraSpacing: Unnecessary spacing detected.
              t('sidebar.date_status.' + date_status) ;     until_date   
                                                       ^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:124:55: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
      t('hubzone_assertions.qualifications_effective') ;     date   
                                                      ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:124:56: C: Style/Semicolon: Do not use semicolons to terminate expressions.
      t('hubzone_assertions.qualifications_effective') ;     date   
                                                       ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_sidebar.html.erb:124:57: C: Layout/ExtraSpacing: Unnecessary spacing detected.
      t('hubzone_assertions.qualifications_effective') ;     date   
                                                        ^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_qualification.html.erb:3:60: C: Rails/Date: Do not use Date.today without zone. Use Time.zone.today instead.
    expires_text = qualification["expires"].to_date < Date.today ? "expired" : "expires"
                                                           ^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_qualification.html.erb:13:92: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                    t('hubzone_assertions.' + expires_text) ;      I18n.l Date.parse(qualification["expires"]), format: :full          
                                                                                           ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_qualification.html.erb:13:93: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                    t('hubzone_assertions.' + expires_text) ;      I18n.l Date.parse(qualification["expires"]), format: :full          
                                                                                            ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_qualification.html.erb:13:94: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                    t('hubzone_assertions.' + expires_text) ;      I18n.l Date.parse(qualification["expires"]), format: :full          
                                                                                             ^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:6:64: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                              t('legend.title') ;       t('legend.title')            
                                                               ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:6:65: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                              t('legend.title') ;       t('legend.title')            
                                                                ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:6:66: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                              t('legend.title') ;       t('legend.title')            
                                                                 ^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:12:100: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                      t('legend.icon_census_tract') ;             t('legend.qct')   
                                                                                                   ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:12:101: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                      t('legend.icon_census_tract') ;             t('legend.qct')   
                                                                                                    ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:12:102: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                      t('legend.icon_census_tract') ;             t('legend.qct')   
                                                                                                     ^^^^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:19:93: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                     t('legend.icon_county') ;             t('legend.qnmc')   
                                                                                            ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:19:94: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                     t('legend.icon_county') ;             t('legend.qnmc')   
                                                                                             ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:25:107: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                              t('legend.icon_indian_land') ;             t('legend.indian_lands')   
                                                                                                          ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:25:108: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                              t('legend.icon_indian_land') ;             t('legend.indian_lands')   
                                                                                                           ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:25:109: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                              t('legend.icon_indian_land') ;             t('legend.indian_lands')   
                                                                                                            ^^^^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:33:108: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                       t('legend.icon_redesignated_county') ;             t('legend.redesignated')   
                                                                                                           ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:33:109: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                       t('legend.icon_redesignated_county') ;             t('legend.redesignated')   
                                                                                                            ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:33:110: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                       t('legend.icon_redesignated_county') ;             t('legend.redesignated')   
                                                                                                             ^^^^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:40:111: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                         t('legend.icon_disaster_area_county') ;             t('legend.qda')   
                                                                                                              ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:40:112: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                         t('legend.icon_disaster_area_county') ;             t('legend.qda')   
                                                                                                               ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:40:113: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                         t('legend.icon_disaster_area_county') ;             t('legend.qda')   
                                                                                                                ^^^^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:48:92: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                      t('legend.icon_brac') ;             t('legend.brac')   
                                                                                           ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:48:93: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                      t('legend.icon_brac') ;             t('legend.brac')   
                                                                                            ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_legend.html.erb:48:94: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                      t('legend.icon_brac') ;             t('legend.brac')   
                                                                                             ^^^^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_body.html.erb:14:51: C: Rails/Date: Do not use Date.today without zone. Use Time.zone.today instead.
              hidden_field_tag "query_date", Date.today   
                                                  ^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_body.html.erb:17:74: C: Rails/OutputSafety: Tagging a string as html safe may be a security risk.
              button_tag '<span class="usa-sr-only">Clear Search</span>'.html_safe, class: "clear-search fa fa-times-circle", tabindex: 0, name: "search-clear", type: "reset"   
                                                                         ^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_map_body.html.erb:18:80: C: Rails/OutputSafety: Tagging a string as html safe may be a security risk.
              button_tag '<span class="usa-sr-only search-icon">Search</span>'.html_safe, id: "hubzone-search-button", tabindex: 2   
                                                                               ^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/search.js.erb:3:38: C: Rails/OutputSafety: Tagging a string as html safe may be a security risk.
                               @body.html_safe      
                                     ^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/map/_local_information.html.erb:15:13: C: Style/SafeNavigation: Use safe navigation (&.) instead of checking if an object exists before calling the method.
         if other_information["congressional_district"] && other_information["congressional_district"][0]   
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/application/_header.html.erb:23:52: C: Rails/OutputSafety: Tagging a string as html safe may be a security risk.
            link_to("<h1>#{t('hubzone_map')}</h1>".html_safe,
                                                   ^^^^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_section_legend.html.erb:2:78: C: Layout/ExtraSpacing: Unnecessary spacing detected.
    image_tag "help/search-bar.png", alt: "hubzone search with autocomplete",  style: "width: 50rem;"   
                                                                             ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:25:117: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                    t('help.elegibility.title_html') ;       t('help.elegibility.title_html')       
                                                                                                                    ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:25:118: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                    t('help.elegibility.title_html') ;       t('help.elegibility.title_html')       
                                                                                                                     ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:25:119: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                                    t('help.elegibility.title_html') ;       t('help.elegibility.title_html')       
                                                                                                                      ^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:28:113: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                  t('help.reporting.title_html') ;       t('help.reporting.title_html')       
                                                                                                                ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:28:114: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                  t('help.reporting.title_html') ;       t('help.reporting.title_html')       
                                                                                                                 ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:28:115: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                                  t('help.reporting.title_html') ;       t('help.reporting.title_html')       
                                                                                                                  ^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:31:118: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                   t('help.understanding.title_html') ;       t('help.understanding.title_html')       
                                                                                                                     ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:31:119: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                   t('help.understanding.title_html') ;       t('help.understanding.title_html')       
                                                                                                                      ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:31:120: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                                   t('help.understanding.title_html') ;       t('help.understanding.title_html')       
                                                                                                                       ^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:34:111: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                 t('help.advanced.title_html') ;       t('help.advanced.title_html')       
                                                                                                              ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:34:112: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                 t('help.advanced.title_html') ;       t('help.advanced.title_html')       
                                                                                                               ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:34:113: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                                 t('help.advanced.title_html') ;       t('help.advanced.title_html')       
                                                                                                                ^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:37:109: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                t('help.version.title_html') ;       t('help.version.title_html')       
                                                                                                            ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:37:110: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                t('help.version.title_html') ;       t('help.version.title_html')       
                                                                                                             ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:37:111: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                                t('help.version.title_html') ;       t('help.version.title_html')       
                                                                                                              ^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:50:118: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                t('help.faq.question_one.title_html') ;       t('help.faq.question_one.title_html')       
                                                                                                                     ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:50:119: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                t('help.faq.question_one.title_html') ;       t('help.faq.question_one.title_html')       
                                                                                                                      ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:53:118: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                t('help.faq.question_two.title_html') ;       t('help.faq.question_two.title_html')       
                                                                                                                     ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:53:119: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                t('help.faq.question_two.title_html') ;       t('help.faq.question_two.title_html')       
                                                                                                                      ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:56:120: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                t('help.faq.question_three.title_html') ;       t('help.faq.question_three.title_html')       
                                                                                                                       ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:56:121: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                t('help.faq.question_three.title_html') ;       t('help.faq.question_three.title_html')       
                                                                                                                        ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:56:122: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                                t('help.faq.question_three.title_html') ;       t('help.faq.question_three.title_html')       
                                                                                                                         ^^^^^^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:59:119: C: Layout/SpaceBeforeSemicolon: Space found before semicolon.
                                                                                t('help.faq.question_four.title_html') ;       t('help.faq.question_four.title_html')       
                                                                                                                      ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:59:120: C: Style/Semicolon: Do not use semicolons to terminate expressions.
                                                                                t('help.faq.question_four.title_html') ;       t('help.faq.question_four.title_html')       
                                                                                                                       ^
/private/var/folders/41/4gl9tm_s4f9f2pg2ms5444n40000gn/workspace/SBA/repos/hubzone/webmap-hz/app/views/help/_navigation.html.erb:59:121: C: Layout/ExtraSpacing: Unnecessary spacing detected.
                                                                                t('help.faq.question_four.title_html') ;       t('help.faq.question_four.title_html')       
                                                                                                                        ^^^^^^

58 files inspected, 70 offenses detected

```

**Comment by jondandois** [comment]
https://sbaone.atlassian.net/wiki/spaces/FEAR/pages/181075976/Ruumba+Integration
Decided we are not going to pursue Ruumba as it introduced more problems than it solved.  Going to favor instead refactoring some views that have too much erb, moving that logic to associated models, controllers as needed.

**Pull request closed without merging**
